### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by olibre** [jdemeule/tidy-tools#1]
1. Add a file "LICENSE" containing your license text.
2. Mention your license within your README.md.
3. Append a short license banner on top of each of your source code file.

Please read https://help.github.com/articles/licensing-a-repository/

Thanks for your talk at [C++FRUG Paris](https://www.meetup.com/User-Group-Cpp-Francophone/events/240136200) ;)

**Comment by jdemeule** [comment]
Thanks for your advice.
License added, issue done.
